### ISSUE TITLE
Allow for htslib on Gentoo Base System/macOS

### ISSUE THREAD

**Issue by xiaoh11** [statgen/bravo_data_prep#10]
## Desired State
Run Cmake on macOS or Gentoo Base System (computecanada remote server) to build htslib

## Context
The previous one is not working on the Gentoo Base System (computecanada). The new version allows htslib to be built on the server.

OS info of server:
```
LSB Version:    n/a
Distributor ID: Gentoo
Description:    Gentoo Base System release 2.6
Release:        2.6
Codename:       n/a
```

**Comment by grosscol** [comment]
Closed by #11
