### ISSUE TITLE
Handling coverage files derived from vcf files

### ISSUE THREAD

**Issue by xiaoh11** [statgen/bravo_data_prep#12]
## Desired State
Need to have scripts that handle generating and pruning coverage data from VCFs instead of depth files from mpileup.

## Context
Getting VCFs from CARTaGENE WGS. Have to compute depth from the raw vcfs instead of using mpileup with crams. As a result, only the mean is calculated and the median is not available.

**Comment by grosscol** [comment]
Closed by #13
